@startuml importarGrados-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":GRADOS_ABIERTO" as GradosAbierto
rectangle #CDEBA5 ":Collaboration CrearGrado" as CrearGrado
rectangle #CDEBA5 ":Collaboration VerGrados" as VerGrados

package importarGrados as "importarGrados()" {
    rectangle #629EF9 ImportarGradosView
    rectangle #b5bd68 GradoController
    rectangle #F2AC4E GradoRepository
    rectangle #F2AC4E Grado
}

GradosAbierto --> ImportarGradosView: importarGrados()

ImportarGradosView -d-> GradoController: cargarArchivoGrados(archivo)
GradoController --> GradoController: validarFormato(archivo)

ImportarGradosView --> GradoController: confirmarImportacion()
GradoController --> GradoRepository: guardarMultiple(listaGrados)
GradoRepository -- Grado

ImportarGradosView ..> CrearGrado: <<include>>
ImportarGradosView ..> VerGrados: completar()

@enduml
