@startuml importarPreguntas-secuencia
skinparam linetype polyline

participant ":PREGUNTAS_ABIERTO" as Sistema
participant ":ImportarPreguntasView" as View
participant ":PreguntaController" as Controller
participant ":PreguntaRepository" as Repository
participant ":Pregunta" as Entity

Sistema -> View: importarPreguntas()
activate View

note over View
Permite seleccionar archivo
Permite elegir asignatura de destino
end note

View -> Controller: importarPreguntas(archivo, asignatura)
activate Controller

loop por cada pregunta
    Controller -> Controller: validarIntegridad()
    
    Controller -> Repository: save(nuevaPregunta)
    activate Repository
    Repository -> Entity: <<create>>
    deactivate Repository
end

View <- Controller: totalPreguntas
deactivate Controller

note over View
Informa sobre preguntas importadas
y posibles errores de formato
end note

@enduml