@startuml exportarAsignaturas-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":Collaboration ExportarConfiguracionGlobal" as ExportGlobal

package exportarAsignaturas as "exportarAsignaturas()" {
    rectangle #629EF9 ExportarAsignaturasView
    rectangle #b5bd68 AsignaturaController
    rectangle #F2AC4E AsignaturaRepository
    rectangle #F2AC4E Asignatura
    rectangle #F2AC4E Exportador
}

ExportGlobal --> ExportarAsignaturasView: <<include>> exportarAsignaturas()

ExportarAsignaturasView -d-> AsignaturaController: exportarDatos(formato)
AsignaturaController --> AsignaturaRepository: obtenerTodas() : List<Asignatura>
AsignaturaController --> Exportador: transformar(datos, formato) : File

AsignaturaRepository -- Asignatura

@enduml
