@startuml exportarPreguntas-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":exportarConfiguracionGlobal" as ExportarGlobal
rectangle #CDEBA5 ":Collaboration CompletarGestion" as CompletarGestion

package exportarPreguntas as "exportarPreguntas()" {
    rectangle #629EF9 ExportarPreguntasView
    rectangle #b5bd68 PreguntaController
    rectangle #F2AC4E Exportador
    rectangle #F2AC4E PreguntaRepository
}

ExportarGlobal --> ExportarPreguntasView: exportarPreguntas()

ExportarPreguntasView -d-> PreguntaController: solicitarExportacion()

PreguntaController --> PreguntaRepository: obtenerPreguntas()
PreguntaController --> Exportador: generarArchivo(datos) : Archivo

ExportarPreguntasView ..> ExportarGlobal: <<include>> [éxito]
ExportarPreguntasView ..> CompletarGestion: <<include>> completarGestion() [cancelación/error]

@enduml
