@startuml importarAlumnos-analisis
skinparam linetype polyline

rectangle #CDEBA5 ":ALUMNOS_ABIERTO" as AlumnosAbierto
rectangle #CDEBA5 ":Collaboration CompletarGestion" as CompletarGestion

package importarAlumnos as "importarAlumnos()" {
    rectangle #629EF9 ImportarAlumnosView
    rectangle #b5bd68 AlumnoController
    rectangle #F2AC4E Importador
    rectangle #F2AC4E AlumnoRepository
}

AlumnosAbierto --> ImportarAlumnosView: importarAlumnos()

ImportarAlumnosView -d-> AlumnoController: procesarImportacion(archivo)

AlumnoController --> Importador: extraerAlumnos(archivo)
AlumnoController --> AlumnoRepository: guardarAlumnos(lista)

ImportarAlumnosView ..> AlumnosAbierto: <<include>> [éxito]
ImportarAlumnosView ..> CompletarGestion: <<include>> completarGestion() [cancelación/error]

@enduml